// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lqZhHhDjxuL2R_Rgvoq6batW7G9LFmE',
    appId: '1:106344653984:web:57d2ad791cb627b72f15c5',
    messagingSenderId: '106344653984',
    projectId: 'puzzlerize-e309d',
    authDomain: 'puzzlerize-e309d.firebaseapp.com',
    storageBucket: 'puzzlerize-e309d.appspot.com',
    measurementId: 'G-H0DGNFWQHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVmzDYA9YU1lU27Mpl_zwDROdcYWw5CY',
    appId: '1:106344653984:android:525c7161b1aa4ef92f15c5',
    messagingSenderId: '106344653984',
    projectId: 'puzzlerize-e309d',
    storageBucket: 'puzzlerize-e309d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98VTk9dPJlz3fKLB0OJ-bETvAJDHXPHE',
    appId: '1:106344653984:ios:93799951fba3536a2f15c5',
    messagingSenderId: '106344653984',
    projectId: 'puzzlerize-e309d',
    storageBucket: 'puzzlerize-e309d.appspot.com',
    iosClientId:
        '106344653984-5mn06q1l8vvrpkf7b2bhhfqod4hc4t7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.puzzlerize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA98VTk9dPJlz3fKLB0OJ-bETvAJDHXPHE',
    appId: '1:106344653984:ios:93799951fba3536a2f15c5',
    messagingSenderId: '106344653984',
    projectId: 'puzzlerize-e309d',
    storageBucket: 'puzzlerize-e309d.appspot.com',
    iosClientId:
        '106344653984-5mn06q1l8vvrpkf7b2bhhfqod4hc4t7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.puzzlerize',
  );
}
